### ISSUE TITLE
lrn2 = cpoImpute(...) %>>% lrn does not have missings property

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlrCPO#42]
```r
lrn = makeLearner("classif.randomForest")
lrn2 = cpoImpute(classes = list(numeric = imputeMax(2))) %>>% lrn
getLearnerProperties(lrn2)
# [1] "numerics"      "factors"       "ordered"       "twoclass"      "multiclass"    "prob"          "class.weights" "oobpreds"      "featimp" 
```

**Comment by jakob-r** [comment]
Ah okay. I have to use `cpoImputeAll`. But then `cpoImputeMax()` should also not add the `missing` property, which it does.

**Comment by mb706** [comment]
The difference between `cpoImputeMax` and `cpoImpute` is that `cpoImpute` does not impute *all* columns, while `cpoImputeMax` does. This behaviour may change when #9 is implemented, when `cpoImpute` will be able to tell from its parameters whether it imputes all columns or not.

**Comment by jakob-r** [comment]
Thank's for clearing me up. Makes sense.
