### ISSUE TITLE
cpoImputeAll does not impute all columns

### ISSUE THREAD

**Issue by notiv** [mlr-org/mlrCPO#55]
That's probably not really an issue and I'm missing something, but I don't understand why the _Age_ column in the following example still contains missing values after applying the retrafo object:
```
library(mlrCPO)
library(dplyr)
library(titanic)

data <- titanic_train
sample <- sample.int(n = nrow(data), size = floor(.7*nrow(data)), replace = F)

train <- titanic_train[sample, ] %>% select(Pclass, Sex, Age, SibSp, Fare, Survived) %>% mutate(Sex = ifelse(Sex == 'male', 0, 1))
test <- titanic_train[-sample,] %>% select(Pclass, Sex, Age, SibSp, Fare, Survived) %>% mutate(Sex = ifelse(Sex == 'male', 0, 1))

# Actually there are more CPOs applied here, but for the shake of simplicity this pipeline consists of only one CPO
cpoPipeline <- cpoImputeAll(classes = list(integer = mlr::imputeMedian(),
                                        numeric = mlr::imputeHist(),
                                        factor = mlr::imputeMode()),
                          dummy.classes = "factor",
                          impute.new.levels = TRUE,
                          recode.factor.levels = TRUE) 

# This imputation works
vtrain <- train %>>% cpoPipeline

# This imputation doesn't
vtest <- test %>>% retrafo(cpoPipeline)

summary(vtest)
```

Any idea what I'm missing here? Thanks!

**Comment by mb706** [comment]
You should be applying `retrafo()` to `vtrain`, not to `cpoPipeline`:
```r
vtrain <- train %>>% cpoPipeline

# This imputation doesn't
vtest <- test %>>% retrafo(vtrain)
```

The intuition here is that the information about the retransformation being performed is created by `cpoPipeline`, but it is *stored* inside the `vtrain` object, together with the resulting data, and then should be retrieved using `retrafo()`.

(`cpoPipeline` does not have a `retrafo` object, and `retrafo` warns about this; in the future it should give an error instead, see #14)

**Comment by notiv** [comment]
Thanks @mb706, it makes sense! I'm closing this.
