### ISSUE TITLE
pkgdown page for main website

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlrCPO#57]
Hi @mb706,

tried to build a pkgdown site to integrate mlrCPO in our new subdomain scheme.
Got some errors caused by the unusual `vignettes/.toc` files. 
Didn't take a deeper look how important they are for your vignettes setup but do you think we can somehow get it compatible with `pkgdown::build_site()` in an easy way?

**Comment by mb706** [comment]
There is no `.toc` file anywhewre in the source tree, can you check if it was created by something your system? Or do you mean the `toc` directory?

**Comment by pat-s** [comment]
> Or do you mean the toc directory?

yes. the dot prefix was a mistake.

You'll see that it raises errors when calling `pkgdown::built_site()`.

**Comment by mb706** [comment]
The presence of the TOC could be made dependent on an environmental variable, I don't know how your deploy script works. Also the PR now adds ~130 files now. they don't need to be part of \*this repo\* to appear on the website, rigth?

**Comment by pat-s** [comment]
> they don't need to be part of *this repo* to appear on the website, rigth?

They do as we just link to the pkgdown site of each pkg (it runs over a CNAME subdomain redirection via gh-pages + netlify). To serve it as a custom domain via netlify, it needs to reside in the repo. 


> The presence of the TOC could be made dependent on an environmental variable, I don't know how your deploy script works.

`pkgdown::build_site()` is called. It picks up custom templates in the `pkgdown` folder. See the examples in the _mlr_ and _mlr3_ repos. 
Would be great if we can have a consistent theme for all pkgdown sites across the org -> so yes, making the ToC dependent on a env variable in combination with the `pkgdown::build_site()` call would be great.

**Comment by mb706** [comment]
https://mlrcpo.mlr-org.com is up.
