### ISSUE TITLE
Save all models from parameter tuning

### ISSUE THREAD

**Issue by notiv** [mlr-org/mlrCPO#64]
Is it possible to save all models that are being created during parameter tuning (and ideally while the training runs)? A similar question has been posted [here](https://stackoverflow.com/questions/40250815/r-mlr-package-is-it-possible-to-save-all-models-from-parameter-tuning) and an mlr wrapper solution has been proposed. Can we do something similar as part of a cpo pipeline, e.g.:
```
cpoPipeline <- cpoImpute(cols=list(a = imputeMedian) %>>% 
   cpoDummyEncode() %>>%
   cpoSaveModel(file) # <- Something like that. Would only run if the pipeline is being executed as part of the training

lrn <- mlr::makeLearner(...)
lrnCPO <- cpoPipeline %>>% lrn

res <- mlr::tuneParams(lrnCPO, task, ...)
```

I understand that saving the model is _not_ preprocessing, but it would be nice if we could do something like that.

**Comment by mb706** [comment]
I think what you are suggesting is not possible with mlrCPO. The CPOs follow the preprocessing paradigm very closely, individual CPO methods only get to see the training and prediction data, and they are only allowed to output datasets. They have bo influence over the training / prediction of the learner model itself. So far I have not had an idea how to allow more general CPOs wothout essentially reimplementing `mlr` wrappers (at which point we would again be at the solution given in your link).
