### ISSUE TITLE
Failure with dev testthat

### ISSUE THREAD

**Issue by hadley** [mlr-org/mlrCPO#78]
```
Error: No test files found
Backtrace:
    █
 1. └─testthat::test_check("mlrCPO", filter = "^_cpo_")
 2.   └─testthat::test_dir(...)
```

Previously this just failed silently, so these tests have probably never been run.

I'm planning to submit testthat to CRAN in about a month.

**Comment by mb706** [comment]
> these tests have probably never been run.

that is false, testthat changed the way it strips prefixes from filenames [in this commit](https://github.com/r-lib/testthat/commit/3c48565a60b5ce832981532fb07146860c491b32).
